"""
This type stub file was generated by pyright.
"""

import os
from av._core import library_versions, pyav_version as __version__, time_base
from av import logging
from av.audio.fifo import AudioFifo
from av.audio.format import AudioFormat
from av.audio.frame import AudioFrame
from av.audio.layout import AudioLayout
from av.audio.resampler import AudioResampler
from av.codec.codec import Codec, codecs_available
from av.codec.context import CodecContext
from av.container import open
from av.format import ContainerFormat, formats_available
from av.packet import Packet
from av.error import *
from av.video.format import VideoFormat
from av.video.frame import VideoFrame

if os.name == 'nt':
    ...
AVError = FFmpegError
