"""
This type stub file was generated by pyright.
"""

class AVDeprecationWarning(DeprecationWarning):
    ...


class AttributeRenamedWarning(AVDeprecationWarning):
    ...


class MethodDeprecationWarning(AVDeprecationWarning):
    ...


class renamed_attr(object):
    """Proxy for renamed attributes (or methods) on classes.
    Getting and setting values will be redirected to the provided name,
    and warnings will be issues every time.

    """
    def __init__(self, new_name) -> None:
        ...
    
    def old_name(self, cls):
        ...
    
    def __get__(self, instance, cls):
        ...
    
    def __set__(self, instance, value):
        ...
    


class method(object):
    def __init__(self, func) -> None:
        ...
    
    def __get__(self, instance, cls):
        ...
    


