"""
This type stub file was generated by pyright.
"""

class CmdProcError(Exception):
    ...


class ConfigureWhileRunningError(CmdProcError):
    ...


class ResultCallbackError(CmdProcError):
    ...


class UnknownCmdError(CmdProcError):
    ...


class InvalidDataError(CmdProcError):
    ...


